version: '3'
services:
  web:
    build: .
    container_name: artnet-controller
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - ARTNET_NODE_IP=192.168.1.221 # IP of the artnet node controller